# You must to set name and define package name as connecting under score!
name: unused_import_remover
description: A tool to remove unused import packages automatically.
version: 1.0.0

homepage: https://github.com/Kate941-su
# You have to explicit sdk version.
environment:
  sdk: '^3.1.0'

# SDK append this field automatically
dependencies:
  glob: ^2.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0